
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KatalogService", targetNamespace = "http://integracja/", wsdlLocation = "http://localhost:8888/katalog?wsdl")
public class KatalogService
    extends Service
{

    private final static URL KATALOGSERVICE_WSDL_LOCATION;
    private final static WebServiceException KATALOGSERVICE_EXCEPTION;
    private final static QName KATALOGSERVICE_QNAME = new QName("http://integracja/", "KatalogService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/katalog?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KATALOGSERVICE_WSDL_LOCATION = url;
        KATALOGSERVICE_EXCEPTION = e;
    }

    public KatalogService() {
        super(__getWsdlLocation(), KATALOGSERVICE_QNAME);
    }

    public KatalogService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KATALOGSERVICE_QNAME, features);
    }

    public KatalogService(URL wsdlLocation) {
        super(wsdlLocation, KATALOGSERVICE_QNAME);
    }

    public KatalogService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KATALOGSERVICE_QNAME, features);
    }

    public KatalogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KatalogService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Katalog
     */
    @WebEndpoint(name = "KatalogPort")
    public Katalog getKatalogPort() {
        return super.getPort(new QName("http://integracja/", "KatalogPort"), Katalog.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Katalog
     */
    @WebEndpoint(name = "KatalogPort")
    public Katalog getKatalogPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://integracja/", "KatalogPort"), Katalog.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KATALOGSERVICE_EXCEPTION!= null) {
            throw KATALOGSERVICE_EXCEPTION;
        }
        return KATALOGSERVICE_WSDL_LOCATION;
    }

}
